name: EcloHammer
version: 1.0-SNAPSHOT
author: Eclosia
main: life.eclosia.hammer.Main
commands:
  hammer:
    description: Commande pour gérer un hammer
    permission: hammer.use
    usage: "Usage: /hammer give <player> <hammer name>"
